module.exports = {
  hiddenFields: [
    "trackedAccounts",
    "currentSnarkWorker",
    "createAccount",
    "createHDAccount",
    "unlockAccount",
    "lockAccount",
    "deleteAccount",
    "reloadAccounts",
    "exportLogs",
    "setStaking",
    "setSnarkWorker",
    "setSnarkWorkFee",
    "setConnectionGatingConfig",
    "addPeers",
    "archivePrecomputedBlock",
    "archiveExtensionalBlock",
  ],
};
