version: "3.9"

services:
  mina-graphql-proxy:
    container_name: mina-graphql-api
    build:
      context: .
      dockerfile: Dockerfile
    image: mina-graphql-proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      MINA_GRAPHQL_HOST: ${MINA_GRAPHQL_HOST:-localhost}
      MINA_GRAPHQL_PORT: ${MINA_GRAPHQL_PORT:-3085}
      MINA_GRAPHQL_PATH: ${MINA_GRAPHQL_PATH:-/graphql}
      MAINTAINER_EMAIL: ${MAINTAINER_EMAIL:-mail@google.com}
      DOMAIN: ${DOMAIN:-google.com}
    restart: always
    volumes:
      - "~/greenlock.d/:/usr/src/app/greenlock.d/"
    command: >
      bash -c 'npx greenlock init --config-dir ./greenlock.d --maintainer-email $MAINTAINER_EMAIL && rm server.js
      && npx greenlock add --subject ${DOMAIN} --altnames "$DOMAIN,www.$DOMAIN"
      && npm start -- --staging'
    networks:
      - mina-network

networks:
  mina-network:
    name: mina-network
    driver: bridge
